// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pluginsapi.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Plugin struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_pluginsapi_1a1873359daa8b49, []int{0}
}
func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (dst *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(dst, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

func (m *Plugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugin) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PluginMetadata struct {
	FullName             string    `protobuf:"bytes,1,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Plugin               *Plugin   `protobuf:"bytes,2,opt,name=plugin" json:"plugin,omitempty"`
	Dependencies         []*Plugin `protobuf:"bytes,3,rep,name=dependencies" json:"dependencies,omitempty"`
	OptionalDependencies []*Plugin `protobuf:"bytes,4,rep,name=optional_dependencies,json=optionalDependencies" json:"optional_dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PluginMetadata) Reset()         { *m = PluginMetadata{} }
func (m *PluginMetadata) String() string { return proto.CompactTextString(m) }
func (*PluginMetadata) ProtoMessage()    {}
func (*PluginMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_pluginsapi_1a1873359daa8b49, []int{1}
}
func (m *PluginMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginMetadata.Unmarshal(m, b)
}
func (m *PluginMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginMetadata.Marshal(b, m, deterministic)
}
func (dst *PluginMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginMetadata.Merge(dst, src)
}
func (m *PluginMetadata) XXX_Size() int {
	return xxx_messageInfo_PluginMetadata.Size(m)
}
func (m *PluginMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PluginMetadata proto.InternalMessageInfo

func (m *PluginMetadata) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *PluginMetadata) GetPlugin() *Plugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

func (m *PluginMetadata) GetDependencies() []*Plugin {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *PluginMetadata) GetOptionalDependencies() []*Plugin {
	if m != nil {
		return m.OptionalDependencies
	}
	return nil
}

type PluginsRegistry struct {
	Plugins              []*Plugin `protobuf:"bytes,1,rep,name=plugins" json:"plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PluginsRegistry) Reset()         { *m = PluginsRegistry{} }
func (m *PluginsRegistry) String() string { return proto.CompactTextString(m) }
func (*PluginsRegistry) ProtoMessage()    {}
func (*PluginsRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_pluginsapi_1a1873359daa8b49, []int{2}
}
func (m *PluginsRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginsRegistry.Unmarshal(m, b)
}
func (m *PluginsRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginsRegistry.Marshal(b, m, deterministic)
}
func (dst *PluginsRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginsRegistry.Merge(dst, src)
}
func (m *PluginsRegistry) XXX_Size() int {
	return xxx_messageInfo_PluginsRegistry.Size(m)
}
func (m *PluginsRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginsRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_PluginsRegistry proto.InternalMessageInfo

func (m *PluginsRegistry) GetPlugins() []*Plugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type Graph struct {
	Nodes                []*Graph_Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Graph) Reset()         { *m = Graph{} }
func (m *Graph) String() string { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()    {}
func (*Graph) Descriptor() ([]byte, []int) {
	return fileDescriptor_pluginsapi_1a1873359daa8b49, []int{3}
}
func (m *Graph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graph.Unmarshal(m, b)
}
func (m *Graph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graph.Marshal(b, m, deterministic)
}
func (dst *Graph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph.Merge(dst, src)
}
func (m *Graph) XXX_Size() int {
	return xxx_messageInfo_Graph.Size(m)
}
func (m *Graph) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph.DiscardUnknown(m)
}

var xxx_messageInfo_Graph proto.InternalMessageInfo

func (m *Graph) GetNodes() []*Graph_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Graph_Node struct {
	Plugin               *Plugin       `protobuf:"bytes,1,opt,name=plugin" json:"plugin,omitempty"`
	Dependencies         []*Graph_Node `protobuf:"bytes,3,rep,name=dependencies" json:"dependencies,omitempty"`
	OptionalDependencies []*Graph_Node `protobuf:"bytes,4,rep,name=optional_dependencies,json=optionalDependencies" json:"optional_dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Graph_Node) Reset()         { *m = Graph_Node{} }
func (m *Graph_Node) String() string { return proto.CompactTextString(m) }
func (*Graph_Node) ProtoMessage()    {}
func (*Graph_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_pluginsapi_1a1873359daa8b49, []int{3, 0}
}
func (m *Graph_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graph_Node.Unmarshal(m, b)
}
func (m *Graph_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graph_Node.Marshal(b, m, deterministic)
}
func (dst *Graph_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph_Node.Merge(dst, src)
}
func (m *Graph_Node) XXX_Size() int {
	return xxx_messageInfo_Graph_Node.Size(m)
}
func (m *Graph_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Graph_Node proto.InternalMessageInfo

func (m *Graph_Node) GetPlugin() *Plugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

func (m *Graph_Node) GetDependencies() []*Graph_Node {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Graph_Node) GetOptionalDependencies() []*Graph_Node {
	if m != nil {
		return m.OptionalDependencies
	}
	return nil
}

// Project represents a file that lists the packages
// your project depends on
type Project struct {
	Dependencies         map[string]string `protobuf:"bytes,1,rep,name=dependencies" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_pluginsapi_1a1873359daa8b49, []int{4}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetDependencies() map[string]string {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func init() {
	proto.RegisterType((*Plugin)(nil), "Plugin")
	proto.RegisterType((*PluginMetadata)(nil), "PluginMetadata")
	proto.RegisterType((*PluginsRegistry)(nil), "PluginsRegistry")
	proto.RegisterType((*Graph)(nil), "Graph")
	proto.RegisterType((*Graph_Node)(nil), "Graph.Node")
	proto.RegisterType((*Project)(nil), "Project")
	proto.RegisterMapType((map[string]string)(nil), "Project.DependenciesEntry")
}

func init() { proto.RegisterFile("pluginsapi.proto", fileDescriptor_pluginsapi_1a1873359daa8b49) }

var fileDescriptor_pluginsapi_1a1873359daa8b49 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xdf, 0x4a, 0xf3, 0x30,
	0x14, 0x27, 0xeb, 0xba, 0x7e, 0x3b, 0xfb, 0xd0, 0x19, 0x26, 0x94, 0x79, 0xe1, 0xd6, 0x2b, 0x41,
	0xa8, 0xa0, 0x22, 0x22, 0xa2, 0x22, 0x8a, 0x57, 0x8e, 0xd1, 0x4b, 0x6f, 0x46, 0x5c, 0x8f, 0x33,
	0x5a, 0x93, 0xd0, 0x66, 0x83, 0xbd, 0x82, 0x8f, 0xe0, 0x9b, 0xf8, 0x04, 0xbe, 0x96, 0xb4, 0x69,
	0xa1, 0xd1, 0xe2, 0x5d, 0xce, 0xef, 0xdf, 0xe9, 0xaf, 0x1c, 0xe8, 0xab, 0x64, 0xb9, 0xe0, 0x22,
	0x63, 0x8a, 0x87, 0x2a, 0x95, 0x5a, 0x06, 0x27, 0xd0, 0x99, 0x16, 0x18, 0xa5, 0xd0, 0x16, 0xec,
	0x0d, 0x7d, 0x32, 0x22, 0x7b, 0xdd, 0xa8, 0x78, 0x53, 0x1f, 0xbc, 0x15, 0xa6, 0x19, 0x97, 0xc2,
	0x6f, 0x15, 0x70, 0x35, 0x06, 0x9f, 0x04, 0x36, 0x8c, 0xf1, 0x1e, 0x35, 0x8b, 0x99, 0x66, 0x74,
	0x07, 0xba, 0x4f, 0xcb, 0x24, 0x99, 0xd5, 0x52, 0xfe, 0xe5, 0xc0, 0x24, 0x4f, 0xda, 0x85, 0x8e,
	0xd9, 0x5d, 0x04, 0xf5, 0x0e, 0xbd, 0xd0, 0xb8, 0xa3, 0x12, 0xa6, 0xfb, 0xf0, 0x3f, 0x46, 0x85,
	0x22, 0x46, 0x31, 0xe7, 0x98, 0xf9, 0xce, 0xc8, 0xa9, 0xcb, 0x2c, 0x92, 0x9e, 0xc3, 0xb6, 0x54,
	0x9a, 0x4b, 0xc1, 0x92, 0x99, 0xe5, 0x6a, 0xdb, 0xae, 0x41, 0xa5, 0xba, 0xa9, 0x89, 0x82, 0x63,
	0xd8, 0x34, 0x7c, 0x16, 0xe1, 0x82, 0x67, 0x3a, 0x5d, 0xd3, 0x31, 0x78, 0xe5, 0xaf, 0xf1, 0x89,
	0x1d, 0x51, 0xe1, 0xc1, 0x17, 0x01, 0xf7, 0x2e, 0x65, 0xea, 0x99, 0x8e, 0xc1, 0x15, 0x32, 0xc6,
	0x4a, 0xda, 0x0b, 0x0b, 0x38, 0x9c, 0xc8, 0x18, 0x23, 0xc3, 0x0c, 0x3f, 0x08, 0xb4, 0xf3, 0xb9,
	0xd6, 0x9b, 0x34, 0xf7, 0x3e, 0x68, 0xec, 0x6d, 0x65, 0xda, 0xdd, 0xaf, 0xfe, 0xee, 0x6e, 0x39,
	0x9b, 0xfb, 0xbf, 0x13, 0xf0, 0xa6, 0xa9, 0x7c, 0xc1, 0xb9, 0xa6, 0x17, 0x3f, 0xd6, 0x9b, 0x4a,
	0xc3, 0xb0, 0xe4, 0xc3, 0xba, 0xf1, 0x56, 0xe8, 0x74, 0x6d, 0x7f, 0xcd, 0xf0, 0x12, 0xb6, 0x7e,
	0x49, 0x68, 0x1f, 0x9c, 0x57, 0x5c, 0x97, 0x37, 0x90, 0x3f, 0xe9, 0x00, 0xdc, 0x15, 0x4b, 0x96,
	0x58, 0x9e, 0x91, 0x19, 0xce, 0x5a, 0xa7, 0xe4, 0xda, 0x7d, 0x70, 0x98, 0xe2, 0x8f, 0x9d, 0xe2,
	0x1c, 0x8f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xdb, 0xa1, 0x1e, 0xa2, 0x02, 0x00, 0x00,
}
